name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - uses: actions/checkout@v2
      - run: bash .ci/build.sh
      - run: bash .ci/test.sh